name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details below.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear description of the feature you'd like to see
      placeholder: What should CXDB be able to do?
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: What problem does this solve? How would you use it?
      placeholder: |
        I want to...
        This would help me...
    validations:
      required: true

  - type: textarea
    id: proposed
    attributes:
      label: Proposed Solution
      description: How do you think this should be implemented?
      placeholder: |
        Add a new API endpoint...
        Or enhance the existing...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: |
        I considered using X but...
        Another option would be Y but...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples
